# Generated by Django 5.2.1 on 2025-07-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_remove_user_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Accounting', 'Accounting'), ('Biological Sciences and Agriculture', 'Biological Sciences and Agriculture'), ('Education', 'Education'), ('Foods, Nutrition and Dietetics', 'Foods, Nutrition and Dietetics'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Information Systems and Computing', 'Information Systems and Computing'), ('Management', 'Management'), ('Mathematics, Chemistry and Physics', 'Mathematics, Chemistry and Physics'), ('Medical Laboratory Science', 'Medical Laboratory Science'), ('Nursing', 'Nursing'), ('Public Health', 'Public Health'), ('Technology and Applied Sciences', 'Technology and Applied Sciences'), ('Theology and Religious Studies', 'Theology and Religious Studies')], max_length=100, null=True),
        ),
    ]
