# Generated by Django 5.2.1 on 2025-07-08 12:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_time'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.activitycategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='certificate_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on featured activities'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='activity',
            name='points_reward',
            field=models.PositiveIntegerField(default=10, help_text='Points awarded for participation', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='activity',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Activity poster or promotional image', null=True, upload_to='activity_posters/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='requirements',
            field=models.TextField(blank=True, help_text='Prerequisites or special requirements'),
        ),
        migrations.AddField(
            model_name='activity',
            name='virtual_link',
            field=models.URLField(blank=True, help_text='Zoom, Teams, or other virtual meeting link'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='points_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('total_attendance', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('volunteer_hours', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('specializations', models.TextField(blank=True, help_text='Areas of expertise or interests')),
                ('activities_created', models.PositiveIntegerField(default=0)),
                ('total_participants_managed', models.PositiveIntegerField(default=0)),
                ('volunteer_hours_coordinated', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
