# Generated by Django 5.2.1 on 2025-07-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_options_activity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='qr_code',
            field=models.CharField(blank=True, help_text='QR code for attendance marking', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='qr_code_used',
            field=models.CharField(blank=True, help_text='QR code that was scanned for this attendance', max_length=100, null=True),
        ),
    ]
