# Generated by Django 5.1.6 on 2025-07-07 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_created_by'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False, help_text='Whether scan resulted in successful check-in')),
                ('error_message', models.TextField(blank=True, help_text='Error message if scan failed')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='activityqrcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='activityqrcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_qr_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityqrcode',
            name='current_uses',
            field=models.IntegerField(default=0, help_text='Current number of scans'),
        ),
        migrations.AddField(
            model_name='activityqrcode',
            name='max_uses',
            field=models.IntegerField(blank=True, default=None, help_text='Max number of scans (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='activityqrcode',
            name='qr_data',
            field=models.TextField(blank=True, help_text='QR code data as JSON string'),
        ),
        migrations.AddField(
            model_name='activityqrcode',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique session identifier'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='qr_code',
            field=models.ForeignKey(blank=True, help_text='QR code used for check-in (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.activityqrcode'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='qr_scanned_at',
            field=models.DateTimeField(blank=True, help_text='When QR was scanned', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activityqrcode',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='activities.activity'),
        ),
        migrations.AddIndex(
            model_name='activityqrcode',
            index=models.Index(fields=['activity', 'is_active'], name='attendance__activit_5d8129_idx'),
        ),
        migrations.AddIndex(
            model_name='activityqrcode',
            index=models.Index(fields=['created_at'], name='attendance__created_07c8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='activityqrcode',
            index=models.Index(fields=['session_id'], name='attendance__session_40f3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='activityqrcode',
            index=models.Index(fields=['code'], name='attendance__code_3b74d3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['activity', 'verification_method'], name='attendance__activit_400ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'checked_in_at'], name='attendance__student_456e54_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['qr_code'], name='attendance__qr_code_b180a4_idx'),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='attendance.activityqrcode'),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_scan_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='qrscanlog',
            index=models.Index(fields=['qr_code', 'scanned_at'], name='attendance__qr_code_d8a19e_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanlog',
            index=models.Index(fields=['activity', 'success'], name='attendance__activit_214681_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanlog',
            index=models.Index(fields=['student', 'scanned_at'], name='attendance__student_b9264a_idx'),
        ),
        migrations.AddIndex(
            model_name='qrscanlog',
            index=models.Index(fields=['success', 'scanned_at'], name='attendance__success_ee2be7_idx'),
        ),
    ]
